---
- name: installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - git
    - make
    - nodejs
    - ruby
    - ruby-dev

- name: installing Ruby Gems
  gem:
    name: "{{ item }}"
    state: present
  sudo: false
  with_items:
    - jekyll
    - github-pages
